/**
 * seed.js – Pre-populates localStorage with demo data if empty.
 * 3 projects, 5 people, 12 issues with varied attributes.
 */

function seedData() {
  // Only seed if no data exists yet
  if (getIssues().length > 0) return;

  const projects = [
    { id: 'proj1', name: 'Customer Portal' },
    { id: 'proj2', name: 'Mobile App' },
    { id: 'proj3', name: 'Backend API' },
  ];

  const people = [
    { id: 'p1', name: 'Alice',   surname: 'Johnson',  email: 'alice@example.com',   username: 'alicej'   },
    { id: 'p2', name: 'Bob',     surname: 'Smith',    email: 'bob@example.com',     username: 'bobs'     },
    { id: 'p3', name: 'Carol',   surname: 'Williams', email: 'carol@example.com',   username: 'carolw'   },
    { id: 'p4', name: 'David',   surname: 'Brown',    email: 'david@example.com',   username: 'davidb'   },
    { id: 'p5', name: 'Eva',     surname: 'Martinez', email: 'eva@example.com',     username: 'evam'     },
  ];

  const issues = [
    {
      id: 'i1',
      summary: 'Login page crashes on mobile browsers',
      description: 'The login form throws a JavaScript error on iOS Safari 16 and Chrome Android. Users cannot authenticate.',
      identifiedBy: 'p3',
      dateIdentified: '2026-01-05',
      projectId: 'proj1',
      assignedTo: 'p1',
      status: 'resolved',
      priority: 'high',
      targetResolutionDate: '2026-01-12',
      actualResolutionDate: '2026-01-11',
      resolutionSummary: 'Fixed a missing polyfill for the fetch API on older mobile browsers.',
    },
    {
      id: 'i2',
      summary: 'Dashboard charts not rendering correctly',
      description: 'The bar charts on the analytics dashboard display incorrect data when the date range spans more than 90 days.',
      identifiedBy: 'p1',
      dateIdentified: '2026-01-15',
      projectId: 'proj1',
      assignedTo: 'p2',
      status: 'open',
      priority: 'medium',
      targetResolutionDate: '2026-02-01',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i3',
      summary: 'API returns 500 on concurrent requests',
      description: 'Under load testing, the /users/bulk endpoint returns HTTP 500 when more than 50 concurrent requests are sent.',
      identifiedBy: 'p2',
      dateIdentified: '2025-12-20',
      projectId: 'proj3',
      assignedTo: 'p4',
      status: 'overdue',
      priority: 'high',
      targetResolutionDate: '2026-01-03',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i4',
      summary: 'Push notifications not delivered on Android',
      description: 'FCM push notifications are silently dropped on Android 14 devices. The issue started after the latest Firebase SDK upgrade.',
      identifiedBy: 'p5',
      dateIdentified: '2026-01-20',
      projectId: 'proj2',
      assignedTo: 'p3',
      status: 'open',
      priority: 'high',
      targetResolutionDate: '2026-02-05',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i5',
      summary: 'Password reset email links expire too quickly',
      description: 'Reset links expire after 15 minutes, causing frustration for users. Requirement states 24-hour validity.',
      identifiedBy: 'p1',
      dateIdentified: '2026-01-18',
      projectId: 'proj3',
      assignedTo: 'p5',
      status: 'resolved',
      priority: 'medium',
      targetResolutionDate: '2026-01-25',
      actualResolutionDate: '2026-01-23',
      resolutionSummary: 'Updated TOKEN_EXPIRY environment variable to 86400 seconds.',
    },
    {
      id: 'i6',
      summary: 'Profile picture upload fails for PNG files',
      description: 'Uploading a PNG profile picture results in a "Unsupported file type" error even though PNG should be allowed per spec.',
      identifiedBy: 'p4',
      dateIdentified: '2026-01-22',
      projectId: 'proj1',
      assignedTo: 'p2',
      status: 'open',
      priority: 'low',
      targetResolutionDate: '2026-02-15',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i7',
      summary: 'App crashes when device language is set to Arabic',
      description: 'RTL language support is missing. The app crashes at startup when Arabic is selected as the device language on the mobile app.',
      identifiedBy: 'p3',
      dateIdentified: '2025-12-10',
      projectId: 'proj2',
      assignedTo: 'p1',
      status: 'overdue',
      priority: 'high',
      targetResolutionDate: '2025-12-31',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i8',
      summary: 'Search results pagination broken after filter',
      description: 'After applying a filter on the search results page, navigating to page 2 resets all filters and shows unfiltered results.',
      identifiedBy: 'p2',
      dateIdentified: '2026-02-01',
      projectId: 'proj1',
      assignedTo: '',
      status: 'open',
      priority: 'medium',
      targetResolutionDate: '2026-02-20',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i9',
      summary: 'Rate limiting not applied to authentication endpoint',
      description: 'The /auth/login endpoint has no rate limit. An attacker can brute-force credentials without restriction.',
      identifiedBy: 'p4',
      dateIdentified: '2026-01-28',
      projectId: 'proj3',
      assignedTo: 'p4',
      status: 'open',
      priority: 'high',
      targetResolutionDate: '2026-02-07',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i10',
      summary: 'Invoice PDF generation uses wrong currency symbol',
      description: 'PDFs generated for EU customers show USD ($) instead of EUR (€). The locale detection logic is incorrect.',
      identifiedBy: 'p5',
      dateIdentified: '2026-01-30',
      projectId: 'proj1',
      assignedTo: 'p5',
      status: 'resolved',
      priority: 'medium',
      targetResolutionDate: '2026-02-10',
      actualResolutionDate: '2026-02-08',
      resolutionSummary: 'Fixed locale detection by reading Accept-Language header properly.',
    },
    {
      id: 'i11',
      summary: 'Dark mode toggle resets on page refresh',
      description: 'User preference for dark mode is not persisted. Every page reload reverts back to light mode.',
      identifiedBy: 'p1',
      dateIdentified: '2026-02-03',
      projectId: 'proj2',
      assignedTo: 'p3',
      status: 'open',
      priority: 'low',
      targetResolutionDate: '2026-03-01',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
    {
      id: 'i12',
      summary: 'Database queries slow when table exceeds 1 million rows',
      description: 'The events table lacks proper indexes. Queries that were fast with small datasets become unacceptably slow at scale.',
      identifiedBy: 'p2',
      dateIdentified: '2026-02-05',
      projectId: 'proj3',
      assignedTo: 'p2',
      status: 'open',
      priority: 'high',
      targetResolutionDate: '2026-02-28',
      actualResolutionDate: '',
      resolutionSummary: '',
    },
  ];

  saveProjects(projects);
  savePeople(people);
  saveIssues(issues);
}
